import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { PortableText, type PortableTextComponents } from '@portabletext/react';
import { fetchPublishedPosts, fetchPostBySlug, urlFor, type SanityPostListItem, type SanityPost } from '@/lib/sanity';
import { formatBlogDate } from '@/lib/blog';
import { blogCoverFor } from '@/lib/blog-covers';
import { frame, Intro, TextLink, Invite, Missing } from './Shell';
export function v2Href(href:string){if(href.startsWith('/')&&!href.startsWith('//'))return /^\/v2(?:\/|$)/.test(href)?href:`/v2${href}`;try{const u=new URL(href);if(['homeimprovementclub.co','www.homeimprovementclub.co'].includes(u.hostname))return v2Href(u.pathname+u.search+u.hash);}catch{/* Relative article anchors remain within this page. */}return href;}
const components:PortableTextComponents={types:{image:({value})=>value?.asset?<figure className="my-8"><img src={urlFor(value)} alt={value.alt||''} loading="lazy" className="w-full"/>{value.alt&&<figcaption className="mt-2 text-sm text-warm-gray">{value.alt}</figcaption>}</figure>:null},marks:{link:({children,value})=>{const href=v2Href(value?.href||'');if(/^(javascript|data|vbscript):/i.test(href))return <>{children}</>;return href.startsWith('/v2')?<Link to={href}>{children}</Link>:<a href={href} target={href.startsWith('http')?'_blank':undefined} rel="noreferrer">{children}</a>}}};
export function Journal(){const [posts,setPosts]=useState<SanityPostListItem[]|null>(null);const [retry,setRetry]=useState(0);useEffect(()=>{let active=true;setPosts(null);fetchPublishedPosts().then(p=>{if(active)setPosts(p)});return()=>{active=false}},[retry]);return <><Intro label="The HIC journal" title="Good questions make a better beginning."><p>Notes on custom homes, multiplex planning, permits and renovations.</p></Intro><section className={`${frame} pb-16`}>{posts===null?<p role="status" className="border-t border-border py-12">Loading the journal…</p>:posts.length===0?<div className="border-y border-border py-10"><h2 className="!text-3xl">No articles available right now.</h2><p className="my-5 text-warm-gray">Please check back for new notes. In the meantime, explore our project planning process.</p><div className="flex flex-wrap items-center gap-6"><TextLink to="/v2/how-it-works">Explore the process</TextLink><button className="min-h-11 underline underline-offset-4" onClick={()=>setRetry(r=>r+1)}>Try again</button></div></div>:<div className="grid gap-x-8 gap-y-12 md:grid-cols-2">{posts.map((p,i)=><article key={p._id} className={i===0?'md:col-span-2':''}><Link to={`/v2/blog/${p.slug}`} className={i===0?'group grid items-center gap-8 md:grid-cols-[1.2fr_1fr]':'group block'}><img src={p.featuredImageUrl||blogCoverFor(p.category)} alt="" loading={i===0?'eager':'lazy'} className="aspect-[3/2] w-full object-cover"/><div className={i===0?'':'mt-5'}><p className="!text-sm text-warm-gray">{p.category} · {formatBlogDate(p.date.slice(0,10))}</p><h2 className="my-4 !text-3xl group-hover:underline">{p.title}</h2><p className="text-warm-gray">{p.excerpt}</p><span className="mt-5 inline-block font-semibold underline underline-offset-4">Read article</span></div></Link></article>)}</div>}</section><Invite/></>}
export function Article(){const {slug}=useParams();const [post,setPost]=useState<SanityPost|null|undefined>();useEffect(()=>{let active=true;setPost(undefined);fetchPostBySlug(slug||'').then(p=>{if(active)setPost(p)});return()=>{active=false}},[slug]);if(post===undefined)return <div className={`${frame} py-20`} role="status">Loading article…</div>;if(!post)return <Missing/>;return <><div className={`${frame} pt-6`}><TextLink to="/v2/blog">All journal articles</TextLink></div><Intro label={post.category} title={post.title}><p>{post.excerpt}</p></Intro><div className={`${frame} pb-10`}><img src={post.featuredImageUrl||blogCoverFor(post.category)} alt={post.featuredImageAlt||''} className="max-h-[650px] w-full object-cover"/></div><article className={`${frame} grid gap-10 pb-16 md:grid-cols-[0.5fr_1.5fr]`}><aside className="text-warm-gray"><p>{formatBlogDate(post.date.slice(0,10))}</p><p className="mt-3">{post.author?.toLowerCase()==='developer'?'Home Improvement Club':post.author||'Home Improvement Club'}</p>{post.readingTimeMinutes&&<p className="mt-3">{post.readingTimeMinutes} minute read</p>}</aside><div className="max-w-3xl space-y-5 [&_h2]:!text-3xl [&_h2]:pt-8 [&_h3]:!text-2xl [&_h3]:pt-5 [&_ul]:list-disc [&_ul]:pl-6 [&_ol]:list-decimal [&_ol]:pl-6 [&_li]:my-2 [&_a]:underline [&_a]:underline-offset-4 [&_blockquote]:border-l-2 [&_blockquote]:border-primary [&_blockquote]:pl-6"><PortableText value={post.body as never} components={components}/></div></article><Invite/></>}
