import { useParams, Link } from 'react-router-dom';
import { ArrowUpRight, Check } from 'lucide-react';
import { SERVICES } from '@/data/services';
import { GALLERY_PROJECTS } from '@/data/projects';
import delta from '@/assets/custom-home-delta.jpg';
import multiplex from '@/assets/multiplex-homes.jpg';
import { frame, section, heading, ButtonLink, TextLink, Intro, Invite, Missing } from './Shell';
import { ProjectTile } from './Projects';

export function Home(){return <>
 <section className={`${frame} grid gap-8 pb-12 pt-10 md:grid-cols-[0.9fr_1.1fr] md:items-center md:gap-10 md:py-14 lg:gap-16`}><div><p className="mb-5 !text-sm font-semibold text-warm-gray">Residential construction · British Columbia</p><h1 className="!text-5xl !leading-[1.04] sm:!text-6xl lg:!text-7xl">A place to build<br/>your future.</h1><p className="mb-8 mt-6 max-w-md !text-lg text-warm-gray">Custom homes, multiplex development and renovations. From the first property conversation to the final walkthrough.</p><ButtonLink to="/v2/contact">Start your project</ButtonLink></div><figure><img src={delta} alt="HIC custom home in Delta with white gables and landscaped driveway" fetchPriority="high" className="aspect-[5/4] w-full object-cover md:aspect-[4/5] lg:max-h-[580px]"/><figcaption className="flex justify-between gap-4 pt-3 text-sm text-warm-gray"><span>Custom home · Delta, BC</span><Link to="/v2/gallery/custom-home-delta" className="underline underline-offset-4">View project</Link></figcaption></figure></section>
 <section className={`${section} border-t border-border`}><div className="max-w-3xl"><h2 className={heading}>From a single home<br/>to what a property can become.</h2><p className="mt-5 text-warm-gray">HIC brings custom homes, multiplex projects and renovations together under one residential construction focus.</p></div><div className="mt-10 grid gap-8 md:grid-cols-2"><article className="border-t border-primary pt-6"><h3 className="!text-3xl">Custom homes</h3><p className="my-4 text-warm-gray">A new home shaped around your property, your priorities and the way you want to live.</p><TextLink to="/v2/services/custom-homes-multiplex#custom-homes">Build your home</TextLink></article><article className="border-t border-primary pt-6"><h3 className="!text-3xl">Multiplex development</h3><p className="my-4 text-warm-gray">Multiple homes. Connected decisions. Start with feasibility, then coordinate design, approvals and construction.</p><TextLink to="/v2/services/custom-homes-multiplex#multiplex">Explore your property’s potential</TextLink></article></div><div className="mt-10 flex flex-col justify-between gap-4 border-y border-border py-6 sm:flex-row sm:items-center"><div><h3 className="!text-2xl">Love where you live. Improve how it works.</h3><p className="mt-2 text-warm-gray">Kitchens, bathrooms, finishes, systems and exteriors.</p></div><TextLink to="/v2/services#renovations">Explore renovations</TextLink></div></section>
 <section className={section}><h2 className={heading}>The work tells the story.</h2><p className="mt-4 max-w-2xl text-warm-gray">Explore custom homes and HIC’s finishing and carpentry contributions to larger developments.</p><div className="mt-10 grid gap-8 md:grid-cols-2">{[GALLERY_PROJECTS[9],GALLERY_PROJECTS[5]].map(p=><ProjectTile key={p.slug} project={p}/>)}</div><div className="mt-8"><TextLink to="/v2/gallery">Explore the full portfolio</TextLink></div></section>
 <section className={`${section} border-y border-border bg-secondary/40`}><h2 className={heading}>A clear path through<br/>a complex project.</h2><div className="mt-10 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{[['Define','Property, priorities and the outcome you want.'],['Plan','Scope, consultants, approvals and budget context.'],['Build','Coordinated work and decisions as construction progresses.'],['Handover','A walkthrough, remaining items and care information.']].map(([t,d],i)=><div key={t}><span className="font-sans text-sm text-warm-gray">0{i+1}</span><h3 className="mb-3 mt-4 !text-2xl">{t}</h3><p className="text-warm-gray">{d}</p></div>)}</div><div className="mt-8"><TextLink to="/v2/how-it-works">Understand the process</TextLink></div></section>
 <section className={section}><div className="max-w-3xl"><h2 className={heading}>Rooted in the Fraser Valley.<br/>Working across Greater Vancouver.</h2><p className="my-5 text-warm-gray">Every project starts with its location. Tell us where you plan to build or renovate, and we’ll discuss the work you have in mind.</p><TextLink to="/v2/areas-we-serve">Find your service area</TextLink></div></section><Invite/>
 </>}
export function Services(){return <><Intro label="Our services" title="Build new. Build more. Make home better."><p>One residential construction focus, with a different starting point for every property.</p></Intro><section className={`${frame} pb-16`}><Link to="/v2/services/custom-homes-multiplex" className="group grid border border-border md:grid-cols-2"><img src={delta} alt="Custom home in Delta" className="aspect-[4/3] h-full w-full object-cover"/><div className="flex flex-col justify-center p-6 md:p-10"><span className="text-sm text-warm-gray">New residential construction</span><h2 className={`${heading} mt-4`}>Custom homes & multiplex</h2><p className="my-5 text-warm-gray">From early property questions to construction and handover. Establish what you want to build and what it will take to get there.</p><span className="flex items-center gap-3 font-semibold group-hover:underline">Explore construction <ArrowUpRight size={18}/></span></div></Link></section><section id="renovations" className={`${section} scroll-mt-6 border-t border-border`}><h2 className={heading}>Renovations, considered as a whole.</h2><p className="mt-5 text-warm-gray">Focused improvements or connected work across your home. Find the right starting point below.</p><div className="mt-10 grid gap-x-8 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{SERVICES.slice(1).map(s=><Link className="group" key={s.slug} to={`/v2/services/${s.slug}`}><img src={s.image} alt={`${s.label} design inspiration`} loading="lazy" className="aspect-[4/3] w-full object-cover"/><h3 className="mt-5 flex items-center justify-between gap-4 !text-2xl group-hover:underline">{s.label}<ArrowUpRight size={20} aria-hidden/></h3><p className="mt-3 text-warm-gray">{s.short}</p></Link>)}</div></section><Invite/></>}
const perspectives: Record<string,{title:string; points:string[]}> = {
 'kitchen-cabinets':{title:'A kitchen works best when every part works together.',points:['Layout & movement','Storage & cabinetry','Surfaces & lighting']},
 bathrooms:{title:'Plan the essentials before choosing the finish.',points:['Daily routines & access','Water & ventilation','Tile & fixtures']},
 lighting:{title:'Give each part of the room a purpose.',points:['Ambient lighting','Task lighting','Accent lighting']},
 flooring:{title:'Start beneath the surface.',points:['Subfloor condition','Material & daily wear','Transitions between rooms']},
 'hvac-electrical':{title:'Comfort starts with a coordinated system.',points:['Existing equipment','Capacity & connections','Upgrade sequence']},
 exterior:{title:'Think about the home as a complete exterior.',points:['Existing condition','Weather exposure','Materials & sequencing']}
};
export function ServiceDetail(){const {slug}=useParams();const s=SERVICES.find(s=>s.slug===slug);if(!s)return <Missing/>;if(slug==='custom-homes-multiplex')return <Construction/>;const perspective=perspectives[s.slug];return <><div className={`${frame} pt-6`}><TextLink to="/v2/services">All services</TextLink></div><section className={`${frame} grid gap-8 pb-14 pt-6 md:grid-cols-2 md:items-center lg:gap-16`}><div><p className="mb-4 text-sm text-warm-gray">{s.title}</p><h1 className="!text-4xl !leading-tight md:!text-6xl">{s.hero}</h1><p className="my-6 text-warm-gray">{s.intro}</p><ButtonLink to={`/v2/contact?service=${s.slug}`}>Plan your {s.slug==='hvac-electrical'?'upgrade':'renovation'}</ButtonLink></div><figure><img src={s.image} alt={`${s.label} inspiration`} className={`w-full object-cover ${s.slug==='lighting'||s.slug==='exterior'?'aspect-[4/3]':'aspect-square'}`}/><figcaption className="pt-2 text-sm text-warm-gray">Design inspiration</figcaption></figure></section>
 <section className={`${section} border-y border-border`}><h2 className={heading}>{perspective.title}</h2>{s.slug==='lighting'?<div className="mt-10 grid gap-8 md:grid-cols-3">{s.benefits.map((b,i)=><article key={b.t}><p className="text-sm text-warm-gray">{perspective.points[i]}</p><h3 className="my-4 !text-2xl">{b.t}</h3><p className="text-warm-gray">{b.d}</p></article>)}</div>:s.slug==='hvac-electrical'||s.slug==='exterior'?<div className="mt-10 space-y-4">{s.benefits.map((b,i)=><details key={b.t} className="border-b border-border pb-4" open={i===0}><summary className="cursor-pointer py-3 font-semibold">{b.t}</summary><p className="pb-4 text-warm-gray">{b.d}</p></details>)}</div>:<div className="mt-10 grid gap-8 md:grid-cols-3">{s.benefits.map((b,i)=><article key={b.t} className="border-l border-border pl-6"><span className="text-sm text-warm-gray">{perspective.points[i]}</span><h3 className="my-3 !text-2xl">{b.t}</h3><p className="text-warm-gray">{b.d}</p></article>)}</div>}</section>
 <section className={`${section} grid gap-8 md:grid-cols-2`}><div><h2 className={heading}>{s.scopeTitle}</h2><p className="mt-5 text-warm-gray">Discuss the parts of your project that need to work together.</p></div><ul className="grid gap-4">{s.sub.map(item=><li key={item} className="flex gap-3"><Check className="mt-1 shrink-0" size={18} aria-hidden/>{item}</li>)}</ul></section><section className={`${frame} pb-14`}><details className="border-y border-border py-4"><summary className="cursor-pointer py-3 text-lg font-semibold">{s.question}</summary><p className="pb-3 pt-3 text-warm-gray">{s.answer}</p></details><div className="mt-8"><TextLink to="/v2/services">Explore other services</TextLink></div></section><Invite service={s.slug}/></>}
function Construction(){const s=SERVICES[0];return <><Intro label="Custom homes & multiplex construction" title="A bigger vision. A considered build."><p>{s.intro}</p></Intro><div className={`${frame} pb-14`}><img src={delta} alt="Custom home in Delta, British Columbia" className="aspect-[4/3] w-full object-cover md:aspect-[21/9]"/></div><section id="custom-homes" className={`${section} grid scroll-mt-6 gap-8 border-t border-border md:grid-cols-[1fr_1.2fr]`}><h2 className={heading}>One home.<br/>Entirely your own.</h2><div><p className="text-warm-gray">A custom home starts with the property and the people who will live there. Bring the intended use, your priorities and any drawings or surveys already available.</p><ul className="my-6 space-y-3">{s.sub.slice(0,1).concat(s.sub.slice(2)).map(t=><li key={t} className="flex gap-3"><Check size={18} className="mt-1 shrink-0"/>{t}</li>)}</ul><ButtonLink to="/v2/contact?service=custom-homes-multiplex">Discuss a custom home</ButtonLink></div></section><section id="multiplex" className={`${section} scroll-mt-6 border-t border-border`}><div className="grid gap-10 md:grid-cols-2"><div><img src={multiplex} alt="Multiplex residential design inspiration" loading="lazy" className="aspect-[4/3] w-full object-cover"/><p className="mt-2 !text-sm text-warm-gray">Multiplex design inspiration</p></div><div><h2 className={heading}>More homes.<br/>One coordinated plan.</h2><p className="my-5 text-warm-gray">Multiplex projects add questions about multiple households, property potential and approvals. Feasibility depends on the site and municipality.</p><p className="mb-6 text-warm-gray">Start with a clear brief. Discuss design and consultant coordination, permit planning, construction and handover in sequence.</p><TextLink to="/v2/investment-partnerships">Explore development partnerships</TextLink></div></div></section><section className={`${section} border-t border-border`}><h2 className={heading}>See the work in context.</h2><div className="mt-8 grid gap-8 md:grid-cols-2">{GALLERY_PROJECTS.filter(p=>p.category==='Custom home').slice(0,2).map(p=><ProjectTile key={p.slug} project={p}/>)}</div></section><section className={`${frame} pb-14`}><details className="border-y border-border py-4"><summary className="cursor-pointer py-3 font-semibold">{s.question}</summary><p className="py-3 text-warm-gray">{s.answer}</p></details><div className="mt-7"><TextLink to="/v2/estimator">Explore a preliminary build estimate</TextLink></div></section><Invite service={s.slug}/></>}
