import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { ArrowUpRight, Menu, X } from 'lucide-react';
import { cn } from '@/lib/utils';
import logo from '@/assets/hic-logo.png';
import { CONTACT_PHONES, getWhatsAppChatUrl, CALENDLY_CONSULT_URL } from '@/lib/contact';
import { trackEvent } from '@/lib/analytics';

export const frame = 'mx-auto w-full max-w-[1440px] px-5 sm:px-8 lg:px-14';
export const section = `${frame} py-14 md:py-20 lg:py-24`;
export const heading = '!text-3xl !leading-[1.12] md:!text-4xl lg:!text-5xl';
export const field = 'w-full min-h-12 rounded-none border border-stone-400 bg-white px-3 py-3 text-base text-charcoal placeholder:text-stone-500 focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/30 disabled:opacity-60';
export const action = 'inline-flex min-h-12 items-center justify-center gap-3 border border-primary bg-primary px-5 py-3 font-sans text-base font-semibold text-primary-foreground transition-colors hover:bg-charcoal focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary disabled:cursor-wait disabled:opacity-60';
export function ButtonLink({ to, children, secondary = false, className }: {to: string; children: ReactNode; secondary?: boolean; className?: string}) {
  return <Link to={to} className={cn(action, secondary && 'bg-transparent text-primary hover:bg-secondary', className)}>{children}<ArrowUpRight size={18} aria-hidden /></Link>;
}
export function TextLink({to, children}: {to: string; children: ReactNode}) {return <Link className="inline-flex min-h-11 items-center gap-3 font-semibold underline decoration-border underline-offset-8 hover:decoration-primary" to={to}>{children}<ArrowUpRight size={17} aria-hidden /></Link>}
export function Intro({label, title, children}: {label: string; title: string; children?: ReactNode}) {return <div className={`${frame} pb-10 pt-10 md:pb-14 md:pt-16`}><p className="mb-5 !text-sm font-semibold tracking-wide text-warm-gray">{label}</p><h1 className="max-w-4xl !text-4xl !leading-[1.08] md:!text-6xl lg:!text-7xl">{title}</h1>{children && <div className="mt-6 max-w-2xl text-lg text-warm-gray">{children}</div>}</div>}
export function Invite({title = 'Your next chapter starts with a conversation.', service}: {title?: string; service?: string}) {return <section className={`${section} border-t border-border`}><div className="grid items-end gap-8 md:grid-cols-[1.5fr_1fr]"><div><h2 className={heading}>{title}</h2><p className="mt-5 text-warm-gray">Bring your property, priorities and ideas. We’ll help clarify the next steps.</p></div><div className="md:justify-self-end"><ButtonLink to={`/v2/contact${service ? `?service=${service}` : ''}`}>Discuss your project</ButtonLink></div></div></section>}
export function ContactMethods(){return <div className="space-y-2">{CONTACT_PHONES.map(p=><a key={p.e164} className="flex min-h-11 items-center font-semibold underline-offset-4 hover:underline" href={`tel:+${p.e164}`} onClick={()=>trackEvent({event:'phone_click',lead_type:'phone',link_location:'contact_info'})}>{p.display}</a>)}<a className="block break-all py-2 underline underline-offset-4" href="mailto:homeimprovementclub.co@gmail.com">homeimprovementclub.co@gmail.com</a><div className="flex flex-wrap gap-x-6"><a className="py-3 underline underline-offset-4" href={getWhatsAppChatUrl()} target="_blank" rel="noreferrer" onClick={()=>trackEvent({event:'whatsapp_click',lead_type:'whatsapp',link_location:'v2_contact'})}>WhatsApp</a><a className="py-3 underline underline-offset-4" href={CALENDLY_CONSULT_URL} target="_blank" rel="noreferrer" onClick={()=>trackEvent({event:'book_consultation_click',lead_type:'calendly',link_location:'v2_contact'})}>Book a 30-minute call</a></div></div>}
const links = [['Services','services'],['Our work','gallery'],['Our process','how-it-works'],['About HIC','about']] as const;
export function ReviewMetadata(){const {pathname}=useLocation();useEffect(()=>{const nodes=[...document.querySelectorAll<HTMLMetaElement>('meta[name="robots"]')];const old=nodes.map(n=>n.content);nodes.forEach(n=>n.content='noindex, nofollow');return()=>nodes.forEach((n,i)=>n.content=old[i]);},[pathname]);return <Helmet><title>Home Improvement Club | V2 Review</title><meta name="robots" content="noindex, nofollow"/></Helmet>}
export default function Shell(){
 const [open,setOpen]=useState(false);const location=useLocation();const trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>setOpen(false),[location.pathname,location.search]);
 return <div data-v2 className="min-h-dvh bg-background font-sans text-charcoal [&_h1]:font-display [&_h2]:font-display [&_h3]:font-display [&_p]:!leading-relaxed [&_a]:decoration-1 [&_button]:touch-manipulation">
 <ReviewMetadata/><a href="#v2-main" className="sr-only z-[100] bg-white p-4 focus:not-sr-only focus:fixed focus:left-4 focus:top-4">Skip to content</a>
 <header className="relative z-40 border-b border-border bg-background"><div className={`${frame} flex h-20 items-center justify-between gap-6`}><Link to="/v2" aria-label="Home Improvement Club home"><img src={logo} alt="Home Improvement Club" className="h-14 w-28 object-contain"/></Link><nav aria-label="Main navigation" className="hidden items-center gap-7 lg:flex">{links.map(([label,path])=><NavLink key={path} to={`/v2/${path}`} className={({isActive})=>cn('py-3 text-base hover:underline underline-offset-8',isActive&&'font-semibold underline')}>{label}</NavLink>)}</nav><div className="flex items-center gap-3"><Link to="/v2/contact" className={cn(action,'hidden sm:inline-flex')}>Start a project<ArrowUpRight size={17} aria-hidden/></Link><button ref={trigger} type="button" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="v2-menu" onClick={()=>setOpen(!open)} className="flex h-12 w-12 items-center justify-center border border-border lg:hidden">{open?<X/>:<Menu/>}</button></div></div>
 {open&&<nav id="v2-menu" aria-label="Mobile navigation" onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);trigger.current?.focus();}}} className={`${frame} border-t border-border pb-6 lg:hidden`}>{[...links,['Journal','blog'],['Contact','contact']].map(([label,path])=><Link key={path} to={`/v2/${path}`} className="block border-b border-border py-4 text-xl">{label}</Link>)}</nav>}</header>
 <main id="v2-main" tabIndex={-1} className="min-w-0 outline-none"><Outlet/></main>
 <footer className={`${frame} border-t border-border pb-8 pt-12`}><div className="grid gap-10 md:grid-cols-2 lg:grid-cols-[1.4fr_1fr_1fr]"><div><img src={logo} alt="Home Improvement Club" className="h-20 w-36 object-contain"/><p className="mt-4 max-w-sm text-warm-gray">Custom homes. Multiplex development. Considered renovations.</p><p className="mt-3 text-warm-gray">Fraser Valley & Greater Vancouver, BC</p></div><nav aria-label="Footer navigation" className="grid grid-cols-2 gap-x-6">{[['Services','services'],['Our work','gallery'],['Our process','how-it-works'],['About','about'],['Service areas','areas-we-serve'],['Testimonials','testimonials'],['Journal','blog'],['Rebates','rebates'],['Partnerships','investment-partnerships'],['Estimator','estimator']].map(([label,path])=><Link key={path} className="py-2 hover:underline underline-offset-4" to={`/v2/${path}`}>{label}</Link>)}</nav><ContactMethods/></div><div className="mt-12 flex flex-wrap justify-between gap-4 border-t border-border pt-6 text-sm text-warm-gray"><span>© {new Date().getFullYear()} Home Improvement Club</span><Link className="underline underline-offset-4" to="/v2/privacy">Privacy policy</Link></div></footer></div>
}
export function Missing(){return <><Intro label="Page not found" title="Let’s get you back on solid ground."><p>This page may have moved, or the address may be incomplete.</p></Intro><div className={`${frame} flex flex-wrap gap-4 pb-20`}><ButtonLink to="/v2">Return home</ButtonLink><ButtonLink to="/v2/gallery" secondary>Explore our work</ButtonLink></div></>}
